# Generated by Django 4.0.3 on 2022-03-20 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=16)),
                ('marital_status', models.CharField(max_length=16)),
                ('Dependents', models.CharField(max_length=16)),
                ('Education', models.CharField(max_length=16)),
                ('Employment', models.CharField(max_length=16)),
                ('credit_history', models.CharField(max_length=16)),
                ('property_area', models.CharField(max_length=16)),
                ('Income', models.IntegerField()),
                ('Coapplicant_income', models.IntegerField()),
                ('Loan_Amount', models.IntegerField()),
                ('Loan_term', models.IntegerField()),
                ('Approved', models.CharField(max_length=16)),
            ],
        ),
    ]
