# Generated by Django 4.0.3 on 2022-03-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanprediction', '0002_rename_loan_amount_applicants_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicants',
            name='firstname',
            field=models.CharField(default='Enter your firstname', max_length=20),
        ),
        migrations.AddField(
            model_name='applicants',
            name='lastname',
            field=models.CharField(default='Enter your lastname', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='coapplicant',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='credit_history',
            field=models.CharField(choices=[('', '-- Do you have an outstanding unpaid loan --'), (1.0, 'Yes'), (0.0, 'No')], max_length=16),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='dependents',
            field=models.CharField(choices=[('', '-- Number of dependents --'), ('0', 'None'), ('1', 'One'), ('2', 'Two'), ('3+', 'More than two')], max_length=16),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='education',
            field=models.CharField(choices=[('', '-- Are you a graduate --'), ('Graduate', 'Yes'), ('Not Graduate', 'No')], max_length=16),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='employment',
            field=models.CharField(choices=[('', '-- Are you self-employed --'), ('Yes', 'Yes'), ('No', 'No')], max_length=16),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='gender',
            field=models.CharField(choices=[('', '-- Select gender --'), ('Male', 'Male'), ('Female', 'Female')], max_length=16),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='income',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='loan_term',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='marital_status',
            field=models.CharField(choices=[('', '-- Select marital status --'), ('Yes', 'Married'), ('No', 'Not married')], max_length=16),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='property_area',
            field=models.CharField(choices=[('', '-- Property area --'), ('Urban', 'Urban'), ('Semiurban', 'Semi-Urban'), ('Rural', 'Rural')], max_length=16),
        ),
    ]
