# Generated by Django 4.0.3 on 2022-03-21 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loanprediction', '0003_applicants_firstname_applicants_lastname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicants',
            name='firstname',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='applicants',
            name='lastname',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
